In [1]:
import numpy as np

In [6]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[2, 3], [5, 6], [8, 7]])
X

array([[2, 3],
       [5, 6],
       [8, 7]])

In [7]:
# tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [8]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([2, 5, 8])

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([5, 6])

In [10]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [14]:
# buat matrix X berukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[2, 3], [5, 6], [8, 7]])
X_pt

tensor([[2, 3],
        [5, 6],
        [8, 7]])

In [15]:
# tampilkan ukuran dari matrix X
X_pt.shape

torch.Size([3, 2])

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
X_pt[:,0]

tensor([2, 5, 8])

In [18]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_pt
X_pt[1,:]

tensor([5, 6])

In [24]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [25]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[2, 3], [5, 6], [8, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 7]], dtype=int32)>

In [26]:
# tampilkan ukuran dari matrix X_tf
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [27]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8], dtype=int32)>

In [28]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8], dtype=int32)>

In [29]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_tf
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>