## Using Numpy


In [2]:
import numpy as np

In [3]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[2, 3, 4], [5, 8, 7]])
X

array([[2, 3, 4],
       [5, 8, 7]])

In [4]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [5]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([2, 5])

In [6]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([5, 8, 7])

## Using Pytorch

In [7]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [8]:
# buat matrix X berukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[2, 3, 4], [5, 8, 7]])
X_pt

tensor([[2, 3, 4],
        [5, 8, 7]])

In [9]:
# tampilkan ukuran dari matrix X
X_pt.shape

torch.Size([2, 3])

In [10]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
X_pt[:,0]

tensor([2, 5])

In [11]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_pt
X_pt[1,:]

tensor([5, 8, 7])

## Using Tensorflow

In [12]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [13]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[2, 3, 4], [5, 8, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 8, 7]], dtype=int32)>

In [14]:
# tampilkan ukuran dari matrix X_tf
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [15]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_tf
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 8, 7], dtype=int32)>