In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([55, 2, 5])
x

array([55,  2,  5])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3,)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0]


np.int64(55)

In [7]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [8]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([55,  2,  5])

In [9]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [10]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([55, 2, 5])
y

array([55,  2,  5])

In [11]:
# tampilkan ukuran dari vector x_t
y.shape

(3,)

In [ ]:
import torch
import tensorflow as tf



In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([55, 2, 5])
x_t