### Soal nomor 1

In [2]:
# 1. Menggunakan NumPy, PyTorch, dan Tensorflow, buatlah matrix ukuran 3x3 lalu hitung nilai Frobenius Norm

import numpy as np
import torch
import tensorflow as tf

In [3]:
X_np = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.linalg.norm(X_np)

np.float64(16.881943016134134)

In [5]:
X_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
X_pt

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [6]:
torch.norm(X_pt)

tensor(16.8819)

In [7]:
X_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
X_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [8]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=16.881942749023438>