### Soal nomor 1

In [ ]:
# 1. Menggunakan NumPy, PyTorch, dan Tensorflow, buatlah matrix ukuran 3x3 lalu hitung nilai Frobenius Norm

import numpy as np
import torch
import tensorflow as tf

In [ ]:
x_np = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.linalg.norm(x_np)

np.float64(16.881943016134134)

In [ ]:
x_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
x_pt

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
torch.norm(x_pt)

In [ ]:
x_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
x_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [ ]:
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=16.881942749023438>