### Soal nomor 1

In [5]:
# 1. Buat matrix A dengan ukuran 2x3 dan vector B berukuran 3x1 menggunakan NumPy

import numpy as np
import torch
import tensorflow as tf

A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8], [9]])

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b

array([[7],
       [8],
       [9]])

In [8]:
# 2. Buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan PyTorch

A_pt = torch.tensor([[10, 11, 12], [13, 14, 15]])
b_pt = torch.tensor([[16], [17], [18]])

In [9]:
A_pt

tensor([[10, 11, 12],
        [13, 14, 15]])

In [10]:
b_pt

tensor([[16],
        [17],
        [18]])

In [11]:
# 3. Buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan Tensorflow

A_tf = tf.Variable([[21, 9, 14], [11, 22, 8]])
b_tf = tf.Variable([[5, 6, 3]])

In [12]:
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[21,  9, 14],
       [11, 22,  8]], dtype=int32)>

In [13]:
b_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[5, 6, 3]], dtype=int32)>

### Soal nomor 2

In [14]:
# 1. Tampilkan ukuran matrix A dan vector b

A.shape, b.shape

((2, 3), (3, 1))

### Soal nomor 3

In [15]:
# 1. Kalikan matrix A dengan vector b

np.dot(A, b)

array([[ 50],
       [122]])

In [16]:
# 2. Kalikan matrix A_pt dengan vector b_pt

torch.matmul(A_pt, b_pt)

tensor([[563],
        [716]])

In [17]:
# 3. Kalikan matrix A_tf dengan vector b_tf

tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[201, 211]], dtype=int32)>

### Soal nomor 4

In [18]:
# 4. Buat matrix B dengan ukuran 3x3 menggunakan NumPy

B = np.array([[25, 12, 8], [19, 10, 28], [3, 27, 11]])

In [19]:
# 5. Buat matrix B_pt dengan ukuran 3x3 menggunakan PyTorch

B_pt = torch.tensor([[15, 21, 13], [24, 6, 17], [5, 29, 22]])

In [20]:
# 6. Buat matrix B_tf dengan ukuran 3x3 menggunakan Tensorflow

B_tf = tf.Variable([[7, 14, 11], [3, 21, 4], [8, 18, 28]])

### Soal nomor 5

In [21]:
 # 1. Kalikan matrix A dengan matrix B

np.dot(A, B)

array([[ 72, 113,  97],
       [213, 260, 238]])

In [22]:
 # 2. Kalikan matrix A_pt dengan matrix B_pt

torch.matmul(A_pt, B_pt)

tensor([[474, 624, 581],
        [606, 792, 737]])

In [23]:
 # 3. Kalikan matrix A_tf dengan matrix B_tf

tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[286, 735, 659],
       [207, 760, 433]], dtype=int32)>

In [24]:
 # 1. Buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

 #Perkalian matrix tidak tergolong komutatif. Ini bisa dibuktikan dengan menjalankan line berikut:
np.dot(B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)