### Soal nomor 1

In [3]:
 # 1. Lakukan perhitungan soal exercise menggunakan Colab

import numpy as np
import torch
import tensorflow as tf

m1_s1 = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
m2_s1 = torch.tensor([[-1], [1], [2]])

torch.matmul(m1_s1, m2_s1)

tensor([[ 5],
        [11],
        [17]])

In [4]:
m1_s2 = torch.eye(3)
m2_s2 = torch.tensor([[-1], [1], [2]], dtype=torch.float32)

torch.matmul(m1_s2, m2_s2)

tensor([[-1.],
        [ 1.],
        [ 2.]])

In [5]:
m1_s3 = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
m2_s3 = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T

torch.matmul(m1_s3, m2_s3)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])