### Soal nomor 1

In [2]:
 # 1. Buat matrix X ukuran 2x2 menggunakan NumPy

import numpy as np
import torch
import tensorflow as tf

import matplotlib.pyplot as plt

X = np.array([[3, 2], [1, 1]])
X

array([[3, 2],
       [1, 1]])

In [3]:
 # 2. Buat invers dari matrix X dan beri nama Xinv menggunakan NumPy

Xinv = np.linalg.inv(X)
Xinv

array([[ 1., -2.],
       [-1.,  3.]])

In [4]:
 # 3. Kalikan X dengan Xinv menggunakan NumPy

np.dot(X, Xinv)

array([[1.0000000e+00, 8.8817842e-16],
       [0.0000000e+00, 1.0000000e+00]])

### Soal nomor 2

In [6]:
 # 1. Selesaikan persamaan berikut menggunakan NumPy, Tensorflow, dan PyTorch
 # 4b + 2c = 4
 # −5b −3c = −7

A_np = np.array([[4, 2], [-5, -3]])
B_np = np.array([4, -7])

X_np = np.linalg.solve(A_np, B_np)

X_np

array([-1.,  4.])

In [7]:
A_torch = torch.tensor([[4.0, 2.0], [-5.0, -3.0]])
B_torch = torch.tensor([4.0, -7.0])

X_torch = torch.linalg.solve(A_torch, B_torch)

X_torch

tensor([-1.,  4.])

In [8]:
A_tf = tf.constant([[4.0, 2.0], [-5.0, -3.0]])
B_tf = tf.constant([[4.0], [-7.0]])

X_tf = tf.linalg.solve(A_tf, B_tf)

X_tf

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.99999946],
       [ 3.999999  ]], dtype=float32)>