### Soal nomor 1

In [1]:
 # 1. Buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

import numpy as np
import torch
import tensorflow as tf

Z_sim = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
Z_sim

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [3]:
Z_sim.T == Z_sim

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Soal nomor 2

In [4]:
 # 1. Menggunakan PyTorch, buatlah matriks identitas I dengan ukuran 4x4

I = torch.eye(4)
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [5]:
 # 2. Menggunakan PyTorch, buatlah vector b_pt dengan ukuran 4x1

b_pt = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)

In [6]:
 # 3. Kalikan matrix I dengan vector b_pt

torch.matmul(I, b_pt)

tensor([[1.],
        [2.],
        [3.],
        [4.]])