In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10,29,38],[47,56,92]])
X

array([[10, 29, 38],
       [47, 56, 92]])

In [4]:
X*3

array([[ 30,  87, 114],
       [141, 168, 276]])

In [5]:
X+3

array([[13, 32, 41],
       [50, 59, 95]])

In [6]:
X-3

array([[ 7, 26, 35],
       [44, 53, 89]])

In [7]:
X*3+3

array([[ 33,  90, 117],
       [144, 171, 279]])

In [8]:
# buat matrix X dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[13,15,16],[27,38,20]])
X_pt

tensor([[13, 15, 16],
        [27, 38, 20]])

In [9]:
X_pt*3

tensor([[ 39,  45,  48],
        [ 81, 114,  60]])

In [10]:
X_pt+3

tensor([[16, 18, 19],
        [30, 41, 23]])

In [11]:
X_pt-3

tensor([[10, 12, 13],
        [24, 35, 17]])

In [12]:
X_pt*3+3

tensor([[ 42,  48,  51],
        [ 84, 117,  63]])

In [13]:
# buat matrix X dengan ukuran 2x3 menggunakan Tensorflow
X_tf = tf.Variable([[10,29,38],[47,56,92]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 29, 38],
       [47, 56, 92]], dtype=int32)>

In [14]:
X_tf*3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 30,  87, 114],
       [141, 168, 276]], dtype=int32)>

In [15]:
X_tf+3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 32, 41],
       [50, 59, 95]], dtype=int32)>

In [16]:
X_tf-3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 26, 35],
       [44, 53, 89]], dtype=int32)>

In [17]:
X_tf*3+3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 33,  90, 117],
       [144, 171, 279]], dtype=int32)>

In [18]:
# buat matrix y dengan ukuran 2x3 menggunakan numpy
y = np.array([[10,20,30],[15,25,35]])
y


array([[10, 20, 30],
       [15, 25, 35]])

In [20]:
# buat matrix y dengan ukuran 2x3 menggunakan pytorch
y_pt = torch.tensor([[10,20,30],[15,25,35]])
y_pt

tensor([[10, 20, 30],
        [15, 25, 35]])

In [21]:
# buat matrix X dengan ukuran 2x3 menggunakan Tensorflow
y_tf = tf.Variable([[10,20,30],[15,25,35]])
y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [15, 25, 35]], dtype=int32)>

In [22]:
X * y

array([[ 100,  580, 1140],
       [ 705, 1400, 3220]])

In [23]:
X_pt * y_pt

tensor([[130, 300, 480],
        [405, 950, 700]])

In [24]:
X_tf * y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 100,  580, 1140],
       [ 705, 1400, 3220]], dtype=int32)>