In [80]:
import numpy as np

In [81]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[25,15,6],[10,19,2]])
X

array([[25, 15,  6],
       [10, 19,  2]])

In [82]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(77)

In [83]:
import tensorflow as tf

In [84]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[20,19,1],[7,12,5]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[20, 19,  1],
       [ 7, 12,  5]], dtype=int32)>

In [85]:
import torch as pt

In [86]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[6,7,8],[8,9,19]])
X_pt

tensor([[ 6,  7,  8],
        [ 8,  9, 19]])

In [87]:
# hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

np.int64(77)

In [88]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [89]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
X_pt.sum()

tensor(57)

In [90]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=0)

array([35, 34,  8])

In [91]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf,axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31,  6], dtype=int32)>

In [92]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
X_pt.sum(axis=0)

tensor([14, 16, 27])

In [93]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=1)

array([46, 31])

In [94]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([40, 24], dtype=int32)>

In [95]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
X_pt.sum(axis=1)

tensor([21, 36])

In [96]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X.min()

np.int64(2)

In [97]:
X_pt.min()

tensor(6)

In [98]:
tf.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [99]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X.max()

np.int64(25)

In [100]:
X_pt.max()

tensor(19)

In [101]:
tf.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [102]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X.mean()

np.float64(12.833333333333334)

In [109]:
X_pt.float().mean()

tensor(9.5000)

In [69]:
tf.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X

In [71]:
X.prod()

np.int64(855000)

In [72]:
X_pt.prod()

tensor(459648)

In [73]:
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=159600>