In [24]:
import numpy as np
import torch
import tensorflow as tf

In [33]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[19,10,16],[25,15,61]])
X

array([[19, 10, 16],
       [25, 15, 61]])

In [34]:
X = X.T
X

array([[19, 25],
       [10, 15],
       [16, 61]])

In [41]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[19,10,16],[25,15,61]])
X_pt

tensor([[19, 10, 16],
        [25, 15, 61]])

In [42]:
X_pt.T

tensor([[19, 25],
        [10, 15],
        [16, 61]])

In [45]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan Tensorflow
X_tf = tf.Variable([[19,10,16],[25,15,61]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[19, 10, 16],
       [25, 15, 61]], dtype=int32)>

In [49]:
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 25],
       [10, 15],
       [16, 61]], dtype=int32)>