In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [4]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [5]:
x_pt = x_pt.T
x_pt

/tmp/ipykernel_15173/2319866093.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  x_pt = x_pt.T


tensor([1, 2, 3])

In [6]:
y_pt = y_pt.T
y_pt

tensor([4, 5, 6])

In [8]:
x_tf = tf.constant(x)
x_tf

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [9]:
y_tf = tf.constant(y)
y_tf

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([4, 5, 6])>

In [10]:
dot_product = np.dot(x, y)
dot_product

np.int64(32)

In [11]:
dot_product_pt = torch.dot(x_pt, y_pt)
dot_product_pt

tensor(32)

In [12]:
dot_product_tf = tf.reduce_sum(tf.multiply(x_tf, y_tf))
dot_product_tf

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [13]:
y = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [18]:
y_transposed = y.T
y_transposed

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [16]:
m = np.array([[25, 10], [-2, 1]])
m

array([[25, 10],
       [-2,  1]])

In [17]:
n = np.array([[-1, 7], [10, 8]])
n

array([[-1,  7],
       [10,  8]])

In [19]:
hadamard_product = np.multiply(m, n)
hadamard_product

array([[-25,  70],
       [-20,   8]])

In [20]:
w = np.array([-1, 2, -2])
w

array([-1,  2, -2])

In [21]:
x = np.array([5, 10, 0])
x

array([ 5, 10,  0])

In [22]:
dot_product_w_x = np.dot(w, x)
dot_product_w_x

np.int64(15)